| Created by Marc Mentat 2022.1 (64bit) Student Edition
*prog_option compatibility:prog_version:ment2022.1
*prog_analysis_class structural
*prog_use_current_job on
*set_default_length_unit millimeter
*set_model_length_unit millimeter
|
*open_model "c:\users\utente\dropbox\pc\desktop\prove senza cricca\protesi spessa\pressione\3.04 mpa\protesi.mud"
*edit_apply Pressione

*apply_dof_value p 3.04
*edit_job job1

*update_job
*submit_job 1 *monitor_job
*save_model
*save_model *quit yes
